version: '3.7'
services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      options:
        max-size: 8g
    volumes:
      - ./data:/workspace/data
      - ./notebooks:/workspace/notebooks
      - ./scripts:/workspace/scripts
      - ./data:/opt/spark/work-dir/data
      - ./scripts:/opt/spark/work-dir/scripts
      - ./source_files:/opt/spark/work-dir/source_files
      - ./conf/log4j.properties:/opt/spark/conf/log4j.properties:ro
      - ./conf/core-site.xml:/opt/spark/conf/core-site.xml
      - ./conf/metastore-site.xml:/opt/spark/conf/hive-site.xml
      - ./conf/hadoop-metrics2-hbase.properties:/opt/spark/conf/hadoop-metrics2-hbase.properties:ro
    env_file:
      - .env.spark
    environment:
      - NOTEBOOK_TOKEN=0b1a81c536fc5df4b9eceec215b312bea0e62eb47a38bdd6
      - NOTEBOOK_PASSWORD=0b1a81c536fc5df4b9eceec215b312bea0e62eb47a38bdd6
      - SPARK_EXTRA_CONF_DIR=/opt/spark/conf
    ports:
      - "4040:4040"  # Spark UI
      - "7077:7077"  # Spark Master
      - "8080:8080"  # Spark UI
      - "4041:4041"
      - "4042:4042"
      - "4043:4043"
      - "8888:8888"
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null && jupyter-lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    depends_on:
      - hive-metastore
      - postgres
  

  postgres:
    image: postgres:11
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metastore_db
    expose:
      - '5432'

  hive-metastore:
    image: 'akashxrepo/akashx-hive-azure-metastore-deltalate:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      # - ./conf/metastore-log4j2.properties:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-log4j2.properties:ro
      # - ./conf/log4j.properties:/opt/spark/conf/log4j.properties:ro
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/metastore-site.xml:/opt/hive/conf/hive-site.xml
      # - ./conf/metastore-log4j2.properties:/opt/hive/conf/metastore-log4j2.properties:ro
      # - ./conf/log4j.properties:/opt/spark/conf/log4j.properties:ro
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      - postgres


volumes:
  postgres_data:

networks:
  akashx-network:
    driver: bridge